server:
  port: 7455
spring:
  # 应用名称
  application:
    name: ks_zuul
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # This route rule used to forward request to activity server
        - id: ks-account
          uri: lb://ks-account
          predicates:
            - Path=/ks-account/**
          filters:
            - StripPrefix=1


#zuul:
#  routes:
#    kssail:  #路由名称，名称任意，保持所有路由名称唯一
#      path: /kssail/**
#      serviceId: ks_account #指定服务id，从Eureka中找到服务的ip和端口
#      strip‐prefix: true #true:代理转发时去掉前缀，false:代理转发时不去掉前缀
eureka:
  instance:
    prefer-ip-address: true # 访问路径可以显示 IP
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7456/eureka/

#zuul:
#  routes:
#    manage‐course: ksaccount #路由名称，名称任意，保持所有路由名称唯一
#    path: /account/**
#    serviceId: ks-account #指定服务id，从Eureka中找到服务的ip和端口
#    strip‐prefix: false #true:代理转发时去掉前缀，false:代理转发时不去掉前缀
#    sensitiveHeaders: #默认zuul会屏蔽cookie，cookie不会传到下游服务，这里设置为空则取消默认的黑名单，如果设置了具体的头信息则不会传到下游服务







#    manage-cms:
#      path: /cms/**
#      serviceId: xc-service-manage-cms
#      strip-prefix: false
#      sensitiveHeaders:
#    manage-sys:
#      path: /sys/**
#      serviceId: xc-service-manage-cms
#      strip-prefix: false
#      sensitiveHeaders:
#    service-ucenter:
#      path: /ucenter/**
#      serviceId: xc-service-ucenter
#      sensitiveHeaders:
#      strip-prefix: false
#    xc-service-manage-order:
#      path: /order/**
#      serviceId: xc-service-manage-order
#      sensitiveHeaders:
#      strip-prefix: false
